language: java

# openjdk6 is not installed by default
# see https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images
addons:
  apt:
    packages:
      - openjdk-6-jdk

# test on mutiple java versions
jdk:
  - openjdk6
  - openjdk7
  - openjdk8
  - oraclejdk8
  - oraclejdk9

# Codecov.io test coverage report
# see https://github.com/codecov/example-java
before_script:
  - pip install --user codecov
after_success:
  - gradle jacocoTestReport
  - codecov

# Gradle specific cache handling
# see http://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
